### ISSUE TITLE
@sky-mavis/tanto-connect dependency missing in example app

### ISSUE THREAD

**Issue by seuchenhund** [skymavis/tanto-kit#23]
Hey team, the example app is not working at the moment, because `@sky-mavis/tanto-connect` is missing in `package.json`.

Steps to reproduce

- clone this repo
- cd `tanto-kit/apps/example/`
- `yarn install`
- `yarn dev`
- Module not found: Can't resolve '@sky-mavis/tanto-connect'

Steps to fix

- `yarn add @sky-mavis/tanto-connect`

**Comment by npnam93** [comment]
Thanks for reporting this. You can resolve the issue by either:
- `yarn build` at the root of the repo to install the necessary packages.
- `yarn add @sky-mavis/tanto-connect` in the example directory to add the missing package manually.

We’ll update the repo soon. Let us know if you encounter any other issues!
